### ISSUE TITLE
Add button to auto-generate team name based on bot names

### ISSUE THREAD

**Issue by NicEastvillage** [ds306e18/cleopetra#79]
If the team only has one bot, the team name should just be the name of the bot. If the team consist of multiple bots, the team name should be generated based on the bots' names.

----
I have been thinking a bit about it, and I think a good approach would be something like:
Take a bit of each bot's name and concatenate them. The bits are decided as follows:
* If the bot's name has the format "[something]Bot", then use [someting], e.g.:
  * "Duibot" => "Dui"
* If the bot's name consists of mulitple words, use the longest one, but never "Psyonix" or words like "of" "by" "the", e.g.:
  * "Beast from the East" => "Beast"
  * "Botimus Prime" =>"Botimus"

So a team consisting of Duibot and Beast from the East should be named "Dui-Beast", and a team consisting of ReliefBot and Psyonix Allstar should be named "Relief-Allstar".

However, this currently have problems with bot names like "Self-driving car" and "PacificScienceScratcher". Self-driving car is known as SDC, but I don't know how to determine when to do abbreviations. We don't want to hardcode bot abbreviations.

**Comment by naturecodevoid** [comment]
I could attempt at this if I don't have to install IntelliJ to run CleoPetra. I believe, after taking a 5 second look at https://docs.gradle.org/current/userguide/command_line_interface.html, that I can run `gradlew.bat \application\run`?

Also where would I put my string mixer module?
I'm thinking in a utilities directory.

I might also try in Python first and then convert to Java, if that's ok.

(sorry for the noob java questions)

**Comment by NicEastvillage** [comment]
Yes, you should be able to compile and run through gradle alone, but I highly recommend Intellij, especially when you start implementing anything in Java.

The utilities package is fine.

Sure. Got any ideas for cases like Self-driving car and PacificScienceScratcher?

**Comment by naturecodevoid** [comment]
Thinking about using the first letter in words for those names. Can't seem to run it through gradle though, with Task :compileJava FAILED and it says it can't find tools.jar, and I can't either.

**Comment by cogitantium** [comment]
I second the use of IntelliJ, there's a free community edition and a fairly easy learning curve.

Regarding abbreviations; we can't rely on capitalisations nor delimiters alone, but together they could probably work well. Any edge-cases could somewhat easily be spotted by the caster.
When to abbreviate should be decided by length, in my opinion. Something like 15-20 chars would probably work well, but is highly dependent on any overlay, if any.

Simple abbreviations could then work by splitting the string on whitespace and delimiters, taking the first character of each substring and uppercasing them before merging to a new string.

If no delimiters or whitespace are present in a string to be abbreviated, then we can probably assume that capitalised characters are the abbreviation and extract them. Unless, of course, they were being saRcAsTic.

**Comment by naturecodevoid** [comment]
I agree with using length to determine abbreviations. On the UI, there could also be an option to change the length for abbreviation, so you can change it depending on your overlay.

We could also not abbreviate if the string without 'bot' in it is short enough. 

Another thought I had was to keep the ability to change the team name manually, if the merging screws up. 

If you saw #82, I have been splitting the strings by a space, but currently I only use the first part of it when there are spaces.

**Comment by cogitantium** [comment]
Settling on a length for configuration is less important, and may not need UI functionality, especially since we don't have a UI-section for settings. Rather the [CleoPetraSettings](https://github.com/ds306e18/cleopetra/blob/master/src/dk/aau/cs/ds306e18/tournament/CleoPetraSettings.java) class could be a place to house it for now. A settings panel should probably be an issue in it self.

I believe we already have the functionality for editing all strings of a team, including the name of the team. That's what I meant by edge-cases being spotted by the caster - maybe I was not clear enough. At any rate, the caster should see if the auto-generated team-name is not proper, and they could then easily edit it.

I did see your draft, looks promising - but why not try it out in Java so that you only have to deal with the idiosyncrasies once?

The java string method `split(regex)` allows you to specify a regex for the splitting, and returns an array of Strings for each split element, this could be used for multiple delimiters.

Regex is also your friend with regards to replacing multiple variations of a string. The `replace` method could be a good bet here, although it doesn't take a regex at first glance. You could misuse `split` for this, as it consumes the match when splitting and then just using the first group, namely the part of the string before the match. 

Gradle is a set-and-forget thing for me, I'm not entirely sure but if everything seems alright, then it's probably fine. I'm currently fiddling with JavaFX libraries which do not want to play along nicely.

Just point the PR to master, we've abandoned dev-staging since it's only really useful when development is frequent and tightly bound between many developers.

**Comment by NicEastvillage** [comment]
As the name of the issues suggest, the auto-naming should be a button. Something like this:
![billede](https://user-images.githubusercontent.com/21122471/61357397-7db3fb80-a878-11e9-89e2-11ea1467d92b.png)
This way the host can still call the teams whatever, but if he just needs a name that describes the teammembers then he can click the auto-name button.

If you get the algorithm to work but run into trouble with the UI I can quickly hook that up for you. Javafx can be annoying.

Regex is definitely your friend here. `([Bb]ot|BOT)\s` will catch both "bot", "Bot", and "BOT" at the end of a word. (Careful with Botimus that starts with "bot")

**Comment by NicEastvillage** [comment]
Added in #95
